### PR TITLE
[task/ci] Adding notifications and dbs to travis

### PR DESCRIPTION
**Pull request by michaelcullum**
TICKET-#34

### CODE REVIEW

**Comment by michaelcullum** [comment]
If you want me to add your emails ask.

**Comment by imkingdavid** [comment]
What's Travis?

**Comment by michaelcullum** [comment]
http://travis-ci.org/#!/phpBB-Blog/phpBB-Blog-for-3.1 - Continous Intergration, Runs tests online, like bamboo.

**Comment by erikfrerejean** [comment]
I've been struggling to have travis run the database things. I'll probably rip the phpBB test suite when I'm home and just use that code.

**Comment by erikfrerejean** [comment]
This one will be replaced by #36

**Pull request closed without merging**
